spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NOMBRE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
api.security.secret=${JWT_SECRET:123456}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate